sudo: required
services: 
  - docker
script:
  - docker build -t yazlai/cypress01 .
  - docker images yazlai/cypress01 

before_deploy:
  - docker login -u yazlai -p Docker2020

deploy:
 provider: script
 script: docker push yazlai/cypress01
on:
  brahc: master