sudo: required
services: 
  - docker
script:
  - docker build -t yazlai/cypress01 .
  - docker images yazlai/cypress01 

before_deploy:
  - docker login -u <DOCKER_USERNAME> -p <DOCKER_PASSWORD>

deploy:
 provider: script
 script: docker push yazlai/cypress01
 on:
  branch: master